
---
name: "Simple GitHub Actions workflow"

on:
  push:
    branches :
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: "Running Date Command"
        run: date
        shell: bash
       
      - name: "Getting OS Details"
        run: cat /etc/os-release
        shell: bash
        
      - name: "User Details"
        run: whoami
        shell: bash
      
      - name: "Current Working Directory Details Before Checkout"
        run: |
          pwd
          ls -al
          
      - name: "Checkout Repository"
        uses: actions/checkout@v3
        
      - name: "Current Working Directory Details After Checkout"
        run: |
          pwd
          ls -al
      
      - name: "Installing Terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"    
          
      - name: "Running script.sh"
        run: |
          chmod +x script.sh
          ./script.sh

